-- +goose Up

-- Equivalente Postgres do schema SQLite. As convenções são idênticas —
-- tempo em BIGINT de milissegundos UTC, enums em TEXT, contadores de 64
-- bits — de modo que o SQL das consultas seja o mesmo nos dois dialetos e
-- a suíte de conformidade rode sem ramificação.

-- Contas de acesso à interface.
CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT   NOT NULL,
    password_hash TEXT   NOT NULL,
    created_at    BIGINT NOT NULL,
    updated_at    BIGINT NOT NULL
);

CREATE UNIQUE INDEX idx_user_username ON app_user (username);

-- Sessões da interface: o cookie carrega o segredo cru, aqui fica o hash.
CREATE TABLE session (
    token_hash TEXT   NOT NULL PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL
);

CREATE INDEX idx_session_expires ON session (expires_at);

-- Credenciais de acesso programático.
CREATE TABLE api_token (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    name         TEXT   NOT NULL,
    token_hash   TEXT   NOT NULL,
    prefix       TEXT   NOT NULL,
    created_at   BIGINT NOT NULL,
    last_used_at BIGINT,
    expires_at   BIGINT
);

CREATE UNIQUE INDEX idx_api_token_hash ON api_token (token_hash);
CREATE INDEX idx_api_token_user ON api_token (user_id);

CREATE TABLE monitor (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   TEXT    NOT NULL,
    type                   TEXT    NOT NULL,
    target                 TEXT    NOT NULL DEFAULT '',
    interval_ms            BIGINT  NOT NULL,
    timeout_ms             BIGINT  NOT NULL,
    confirmation_threshold INTEGER NOT NULL DEFAULT 3,
    degraded_latency_ms    BIGINT  NOT NULL DEFAULT 0,
    -- Configuração do checker, opaca para o banco. Uma coluna por opção de
    -- cada tipo faria a tabela ganhar campos nuláveis a cada checker novo.
    config                 TEXT    NOT NULL DEFAULT '{}',
    parent_id              BIGINT           REFERENCES monitor (id) ON DELETE SET NULL,
    -- INTEGER em vez de BOOLEAN de propósito: SQLite não tem tipo booleano,
    -- e igualar aqui elimina uma divergência de dialeto no código que lê e
    -- escreve a coluna. O custo é estilístico; o ganho é uma implementação
    -- de store genuinamente compartilhada.
    enabled                INTEGER NOT NULL DEFAULT 1,
    tags                   TEXT    NOT NULL DEFAULT '[]',
    created_at             BIGINT  NOT NULL,
    updated_at             BIGINT  NOT NULL
);

CREATE UNIQUE INDEX idx_monitor_name ON monitor (name);
CREATE INDEX idx_monitor_parent ON monitor (parent_id);

CREATE TABLE heartbeat (
    monitor_id BIGINT  NOT NULL REFERENCES monitor (id) ON DELETE CASCADE,
    probe_id   TEXT    NOT NULL DEFAULT 'local',
    ts         BIGINT  NOT NULL,
    status     TEXT    NOT NULL,
    latency_ms BIGINT  NOT NULL DEFAULT 0,
    message    TEXT    NOT NULL DEFAULT ''
);

CREATE INDEX idx_heartbeat_monitor_ts ON heartbeat (monitor_id, ts);
CREATE INDEX idx_heartbeat_ts ON heartbeat (ts);

CREATE TABLE rollup (
    monitor_id      BIGINT           NOT NULL REFERENCES monitor (id) ON DELETE CASCADE,
    probe_id        TEXT             NOT NULL DEFAULT 'local',
    resolution      TEXT             NOT NULL,
    bucket_start    BIGINT           NOT NULL,

    total           BIGINT           NOT NULL DEFAULT 0,
    up              BIGINT           NOT NULL DEFAULT 0,
    down            BIGINT           NOT NULL DEFAULT 0,
    degraded        BIGINT           NOT NULL DEFAULT 0,
    -- Checks que rodaram sem observar nada; fora do cálculo de SLA.
    unknown         BIGINT           NOT NULL DEFAULT 0,

    latency_samples BIGINT           NOT NULL DEFAULT 0,
    latency_avg_ms  DOUBLE PRECISION NOT NULL DEFAULT 0,
    latency_min_ms  DOUBLE PRECISION NOT NULL DEFAULT 0,
    latency_max_ms  DOUBLE PRECISION NOT NULL DEFAULT 0,
    latency_p50_ms  DOUBLE PRECISION NOT NULL DEFAULT 0,
    latency_p95_ms  DOUBLE PRECISION NOT NULL DEFAULT 0,
    latency_p99_ms  DOUBLE PRECISION NOT NULL DEFAULT 0,

    PRIMARY KEY (monitor_id, probe_id, resolution, bucket_start)
);

CREATE INDEX idx_rollup_prune ON rollup (resolution, bucket_start);

-- Último sinal recebido de cada monitor push. Separado das batidas porque
-- o checker de push grava uma a cada verificação; ler a última batida
-- seria ler a que ele mesmo acabou de escrever.
CREATE TABLE push_state (
    monitor_id BIGINT NOT NULL PRIMARY KEY REFERENCES monitor (id) ON DELETE CASCADE,
    last_push  BIGINT NOT NULL
);

CREATE TABLE rollup_state (
    resolution  TEXT   NOT NULL PRIMARY KEY,
    last_bucket BIGINT NOT NULL
);

-- +goose Down
DROP TABLE rollup_state;
DROP TABLE push_state;
DROP TABLE rollup;
DROP TABLE heartbeat;
DROP TABLE monitor;
DROP TABLE api_token;
DROP TABLE session;
DROP TABLE app_user;
