-- +goose Up

-- Equivalente Postgres do schema de páginas públicas. As convenções são
-- as mesmas do arquivo SQLite — tempo em BIGINT de milissegundos UTC,
-- enums em TEXT — e as razões de cada decisão estão comentadas lá, para
-- não divergirem em duas cópias.
--
-- Booleano é INTEGER também aqui, como no restante deste schema. O
-- Postgres tem BOOLEAN, mas usá-lo obrigaria a um segundo caminho de
-- leitura em Go só neste dialeto, e a suíte de conformidade deixaria de
-- exercitar o mesmo código nos dois bancos.

CREATE TABLE status_page (
    id           BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug         TEXT    NOT NULL,
    title        TEXT    NOT NULL,
    description  TEXT    NOT NULL DEFAULT '',
    show_latency INTEGER NOT NULL DEFAULT 0,
    time_zone    TEXT    NOT NULL DEFAULT '',
    enabled      INTEGER NOT NULL DEFAULT 1,
    created_at   BIGINT  NOT NULL,
    updated_at   BIGINT  NOT NULL
);

CREATE UNIQUE INDEX idx_status_page_slug ON status_page (slug);

CREATE TABLE status_page_group (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id  BIGINT NOT NULL REFERENCES status_page (id) ON DELETE CASCADE,
    name     TEXT   NOT NULL,
    position INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_status_page_group_page ON status_page_group (page_id, position);

CREATE TABLE status_page_component (
    page_id    BIGINT  NOT NULL REFERENCES status_page (id) ON DELETE CASCADE,
    monitor_id BIGINT  NOT NULL REFERENCES monitor (id) ON DELETE CASCADE,
    -- SET NULL: desfazer um agrupamento reorganiza a página, não
    -- despublica o componente.
    group_id   BIGINT           REFERENCES status_page_group (id) ON DELETE SET NULL,
    label      TEXT    NOT NULL DEFAULT '',
    position   INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (page_id, monitor_id)
);

CREATE INDEX idx_status_page_component_group ON status_page_component (group_id);

CREATE TABLE announcement (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT    NOT NULL,
    impact      TEXT    NOT NULL,
    phase       TEXT    NOT NULL,
    global      INTEGER NOT NULL DEFAULT 0,
    -- SET NULL: o que foi comunicado publicamente é registro e sobrevive
    -- à exclusão do monitor que originou o incidente.
    incident_id BIGINT           REFERENCES incident (id) ON DELETE SET NULL,
    started_at  BIGINT  NOT NULL,
    resolved_at BIGINT,
    created_at  BIGINT  NOT NULL,
    updated_at  BIGINT  NOT NULL
);

CREATE INDEX idx_announcement_started ON announcement (started_at);

CREATE TABLE announcement_component (
    announcement_id BIGINT NOT NULL REFERENCES announcement (id) ON DELETE CASCADE,
    monitor_id      BIGINT NOT NULL REFERENCES monitor (id) ON DELETE CASCADE,
    PRIMARY KEY (announcement_id, monitor_id)
);

CREATE TABLE announcement_update (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id BIGINT NOT NULL REFERENCES announcement (id) ON DELETE CASCADE,
    phase           TEXT   NOT NULL,
    body            TEXT   NOT NULL,
    published_at    BIGINT NOT NULL
);

CREATE INDEX idx_announcement_update_parent
    ON announcement_update (announcement_id, published_at);

-- +goose Down
DROP TABLE announcement_update;
DROP TABLE announcement_component;
DROP TABLE announcement;
DROP TABLE status_page_component;
DROP TABLE status_page_group;
DROP TABLE status_page;
